# 参考: http://geekyplatypus.com/making-your-dockerised-php-application-even-better/
version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
          context: ./
          dockerfile: ./php.dockerfile
        volumes:
            - ./code:/code
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - code-network
    composer:
        image: composer/composer:php7
        restart: 'no'
        command: install
        working_dir: /code
        volumes:
            - ./code:/code
        networks: 
            - code-network
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=docker
            - MYSQL_USER=docker-container
            - MYSQL_PASSWORD=YqukX1!m!eBeP
        networks:
            - code-network
    redis:
        image: redis:5.0-alpine
        ports:
            - "16379:6379"

networks:
    code-network:
        driver: bridge